services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-scryframe
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: scryframe_db
    ports:
      - "5433:5432"